creatures = {
    'fighter1': {'MAIN': {'name': '', 'level': '1', 'xp': '0', 'max_hp': '12', 'ac': '17', 'physical_state': 'normal', 'max_speed': '30', 'hit_dice': ['10.1'], 'defined_initiative': '-1', 'char_class': 'fighter', 'passive_perception': '13', 'proficiency_bonus': 2}, 'ABILITIES': {'con': '15', 'int': '11', 'wis': '13', 'cha': '14', 'dex': '9', 'str': '16'}, 'SKILLS': {'athletics': '5', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '2', 'arcana': '0', 'survival': '1', 'perception': '3', 'medicine': '1', 'insight': '1', 'animal_handling': '1', 'persuasion': '4', 'performance': '2', 'intimidation': '2', 'deception': '2', 'stealth': '-1', 'acrobatics': '-1', 'sleigh_of_hand': '-1'}, 'PERKS': ['second_wind', 'fighting_style_defense', 'position_of_privilege'], 'EQUIPMENT': {'equipment': ['chain mail', 'greataxe', '3 javelin', 'backpack', 'blanket', 'tinderbox', '2 rations', 'waterskin', 'clothes fine', 'signet ring', 'scroll of pedigree'], 'equipment on': ['greataxe', 'javelin'], 'money': ['25 gp']}, 'SPECIAL': [], 'ID': 'fighter1'},
    'cleric1': {'MAIN': {'name': '', 'level': '1', 'xp': '0', 'max_hp': '11', 'ac': '18', 'physical_state': 'normal', 'max_speed': '25', 'hit_dice': ['8.1'], 'defined_initiative': '-1', 'char_class': 'cleric', 'passive_perception': '13', 'proficiency_bonus': 2}, 'ABILITIES': {'con': '15', 'int': '10', 'wis': '16', 'cha': '12', 'dex': '8', 'str': '14'}, 'SKILLS': {'athletics': '4', 'religion': '2', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '0', 'survival': '3', 'perception': '3', 'medicine': '5', 'insight': '3', 'animal_handling': '3', 'persuasion': '1', 'performance': '1', 'intimidation': '3', 'deception': '1', 'stealth': '-1', 'acrobatics': '-1', 'sleigh_of_hand': '-1'}, 'PERKS': ['disciple_of_life', 'dwarven_resilience', 'dwarven_toughness'], 'EQUIPMENT': {'equipment': ['chain mail', 'shield', 'warhammer', '2 handaxe', 'holy symbol', 'backpack', 'crowbar', 'hammer', '10 piton', '10 torch', 'tinderbox', '10 rations', 'waterskin', '50 feet of hempen rope', 'masons tool', 'dagger', 'deck of playing cards', 'clothes common', 'pouch', 'rank insignia'], 'equipment on': ['warhammer', 'handaxe'], 'money': ['10 gp']}, 'SPECIAL': [], 'ID': 'cleric1'},
    'rogue1': {'MAIN': {'name': '', 'level': '1', 'xp': '0', 'max_hp': '9', 'ac': '14', 'physical_state': 'normal', 'max_speed': '25', 'hit_dice': ['8.1'], 'defined_initiative': '3', 'char_class': 'rogue', 'passive_perception': '10', 'proficiency_bonus': 2}, 'ABILITIES': {'con': '12', 'int': '13', 'wis': '10', 'cha': '16', 'dex': '16', 'str': '8'}, 'SKILLS': {'athletics': '-1', 'religion': '1', 'nature': '1', 'investigation': '3', 'history': '1', 'arcana': '1', 'survival': '0', 'perception': '0', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '3', 'performance': '5', 'intimidation': '3', 'deception': '5', 'stealth': '7', 'acrobatics': '5', 'sleigh_of_hand': '5'}, 'PERKS': ['sneak_attack', 'thieves_cant', 'lucky', 'brave', 'halfling_nimbleness', 'naturally_stealthy', 'criminal_contact'], 'EQUIPMENT': {'equipment': ['shortsword', 'shortbow', '20 arrow', 'leather armor', 'thieves tools', 'backpack', 'bell', '5 candle', 'crowbar', 'hammer', '10 pitons', 'rope hempen', 'hooded lantern', '2 flask of oil', '5 rations', 'tinderbox', 'waterskin', 'crowbar', 'common clothes', 'pouch'], 'equipment on': ['shortsword', 'shortbow'], 'money': ['15 gp']}, 'SPECIAL': [], 'ID': 'rogue1'},
    'wizard1': {'MAIN': {'name': '', 'level': '1', 'xp': '0', 'max_hp': '8', 'ac': '12', 'physical_state': 'normal', 'max_speed': '30', 'hit_dice': ['6.1'], 'defined_initiative': '2', 'char_class': 'wizard', 'passive_perception': '10', 'proficiency_bonus': 2}, 'ABILITIES': {'con': '14', 'int': '16', 'wis': '12', 'cha': '8', 'dex': '15', 'str': '10'}, 'SKILLS': {'athletics': '0', 'religion': '5', 'nature': '3', 'investigation': '5', 'history': '3', 'arcana': '5', 'survival': '1', 'perception': '3', 'medicine': '1', 'insight': '3', 'animal_handling': '1', 'persuasion': '-1', 'performance': '-1', 'intimidation': '-1', 'deception': '-1', 'stealth': '2', 'acrobatics': '2', 'sleigh_of_hand': '2'}, 'PERKS': ['spellcasting', 'arcane_recovery', 'darkvision', 'fey_ancestry', 'trance', 'shelter_of_the_faithful'], 'EQUIPMENT': {'equipment': ['shortsword', 'component pouch', 'spellbook', 'backpack', 'bottle of ink', 'ink pen', '10 sheet of parchment', 'small knife', 'tome of historical lore', 'holy symbol', 'prayer book', 'common clothes', 'pouch'], 'equipment on': ['shortsword'], 'money': ['5 gp']}, 'SPECIAL': [], 'ID': 'wizard1'},
    'fighter1b': {'MAIN': {'name': '', 'level': '1', 'xp': '0', 'max_hp': '12', 'ac': '14', 'physical_state': 'normal', 'max_speed': '30', 'hit_dice': ['10.1'], 'defined_initiative': '3', 'char_class': 'fighter', 'passive_perception': '13', 'proficiency_bonus': 2}, 'ABILITIES': {'con': '15', 'int': '11', 'wis': '13', 'cha': '9', 'dex': '16', 'str': '14'}, 'SKILLS': {'athletics': '2', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '2', 'arcana': '0', 'survival': '3', 'perception': '3', 'medicine': '1', 'insight': '1', 'animal_handling': '3', 'persuasion': '-1', 'performance': '-1', 'intimidation': '-1', 'deception': '-1', 'stealth': '3', 'acrobatics': '3', 'sleigh_of_hand': '3'}, 'PERKS': ['second_wind', 'fighting_style_archery', 'rustic_hospitality'], 'EQUIPMENT': {'equipment': ['leather armor', 'longbow', '20 arrow', 'greatsword', 'backpack', 'bedroll', 'mess kit', 'tinderbox', '10 torch', '10 rations', 'waterskin', 'rope hempen', 'carpenters tools', 'shovel', 'iron pot', 'common clothes', 'pouch'], 'equipment on': ['greatsword', 'longbow'], 'money': ['10 gp']}, 'SPECIAL': [], 'ID': 'fighter1b'},
    'bugbear': {'MAIN': {'name': '', 'level': '1', 'xp': '200', 'max_hp': '27', 'ac': '16', 'physical_state': 'normal', 'max_speed': '30', 'hit_dice': ['8', '2', '2'], 'defined_initiative': '0', 'char_class': 'bugbear(goblinoid)', 'passive_perception': '10'}, 'ABILITIES': {'con': '13', 'int': '8', 'wis': '11', 'cha': '9', 'dex': '14', 'str': '15'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '0', 'survival': '2', 'perception': '0', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '0', 'deception': '0', 'stealth': '6', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['brute', 'darkvision', 'surprise_attack'], 'EQUIPMENT': {'equipment': ['hide', 'shield', 'morningstar', 'javelin', 'random(1)'], 'equipment on': ['morningstar', 'javelin'], 'money': ['random(2)']}, 'SPECIAL': [], 'ID': 'bugbear'},
    'commoner': {'MAIN': {'name': '', 'level': '0', 'xp': '10', 'max_hp': '4', 'ac': '10', 'physical_state': 'normal', 'max_speed': '30', 'hit_dice': ['4.1'], 'defined_initiative': '0', 'char_class': 'commoner', 'passive_perception': '10'}, 'ABILITIES': {'con': '10', 'int': '10', 'wis': '10', 'cha': '10', 'dex': '10', 'str': '10'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '0', 'survival': '0', 'perception': '0', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '0', 'deception': '0', 'stealth': '0', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': [], 'EQUIPMENT': {'equipment': ['club', 'clothes', 'random(0)'], 'equipment on': ['club'], 'money': ['random(1)']}, 'SPECIAL': [], 'ID': 'commoner'},
    'cultist': {'MAIN': {'name': '', 'level': '0', 'xp': '25', 'max_hp': '9', 'ac': '12', 'physical_state': 'normal', 'max_speed': '30', 'hit_dice': ['6', '1', '1'], 'defined_initiative': '0', 'char_class': 'cultist', 'passive_perception': '10'}, 'ABILITIES': {'con': '10', 'int': '10', 'wis': '11', 'cha': '10', 'dex': '12', 'str': '11'}, 'SKILLS': {'athletics': '0', 'religion': '2', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '0', 'survival': '0', 'perception': '0', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '0', 'deception': '2', 'stealth': '0', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['devotion'], 'EQUIPMENT': {'equipment': ['leather armor', 'scimitar', 'random(1)'], 'equipment on': ['scimitar'], 'money': ['random(1)']}, 'SPECIAL': [], 'ID': 'cultist'},
    'doppelganger': {'MAIN': {'name': 'Doppelganger', 'level': '3', 'xp': '700', 'max_hp': '52', 'ac': '14', 'physical_state': 'normal', 'max_speed': '30', 'hit_dice': ['6', '1', '4'], 'defined_initiative': '0', 'char_class': 'shapechanger', 'passive_perception': '11'}, 'ABILITIES': {'con': '14', 'int': '11', 'wis': '12', 'cha': '14', 'dex': '18', 'str': '11'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '0', 'survival': '0', 'perception': '0', 'medicine': '0', 'insight': '3', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '0', 'deception': '6', 'stealth': '0', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['ambush', 'surprise_attack', 'darkvision', 'multiattack', 'read_thoughts'], 'EQUIPMENT': {'equipment': ['random(3)'], 'equipment on': [''], 'money': ['random(1)']}, 'SPECIAL': ['immunity.mental_state.charmed'], 'ID': 'doppelganger'},
    'evil_mage': {'MAIN': {'name': '', 'level': '1', 'xp': '200', 'max_hp': '22', 'ac': '12', 'physical_state': 'normal', 'max_speed': '30', 'hit_dice': ['8', '1', '-1'], 'defined_initiative': '0', 'char_class': 'evil mage(humanoid)', 'passive_perception': '11'}, 'ABILITIES': {'con': '11', 'int': '17', 'wis': '12', 'cha': '11', 'dex': '14', 'str': '9'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '5', 'arcana': '5', 'survival': '0', 'perception': '0', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '0', 'deception': '0', 'stealth': '0', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['spellcasting'], 'EQUIPMENT': {'equipment': ['clothes', 'quarterstaff', '5 candle', 'random(2)'], 'equipment on': ['quarterstaff'], 'money': ['random(3)']}, 'SPECIAL': [], 'ID': 'evil_mage'},
    'flameskull': {'MAIN': {'name': 'Flameskull', 'level': '4', 'xp': '1000', 'max_hp': '40', 'ac': '13', 'physical_state': 'flying', 'max_speed': '40', 'hit_dice': ['6', '3', ' 0', ' ranged'], 'defined_initiative': '0', 'char_class': 'Tiny undead', 'passive_perception': '12'}, 'ABILITIES': {'con': '14', 'int': '16', 'wis': '10', 'cha': '11', 'dex': '17', 'str': '1'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '5', 'survival': '0', 'perception': '2', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '0', 'deception': '0', 'stealth': '0', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['darkvision', 'illumination', 'magic_resistance', 'rejuvenation', 'spellcasting', 'multiattack', 'fire_ray(main)'], 'EQUIPMENT': {'equipment': ['random(3)'], 'equipment on': [''], 'money': ['random(1)']}, 'SPECIAL': ['resistance.damage.lightning', 'resistance.damage.necrotic', 'resistance.damage.piercing', 'immunity.damage.cold', 'immunity.damage.fire', 'immunity.damage.poison', 'immunity.mental_state.charmed', 'immunity.mental_state.frightened', 'immunity.physical_state.paralyzed', 'immunity.physical_state.poisoned'], 'ID': 'flameskull'},
    'ghoul': {'MAIN': {'name': 'Ghoul', 'level': '1', 'xp': '200', 'max_hp': '22', 'ac': '12', 'physical_state': 'normal', 'max_speed': '30', 'hit_dice': ['4', '2', '2'], 'defined_initiative': '0', 'char_class': 'undead', 'passive_perception': '10'}, 'ABILITIES': {'con': '10', 'int': '7', 'wis': '10', 'cha': '6', 'dex': '15', 'str': '13'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '0', 'survival': '0', 'perception': '0', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '0', 'deception': '0', 'stealth': '0', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['bite', 'darkvision', 'claws(main)'], 'EQUIPMENT': {'equipment': ['random(0)'], 'equipment on': [''], 'money': ['random(0)']}, 'SPECIAL': ['immunity.physical_state.poisoned', 'immunity.mental_state.charmed', 'immunity.damage.poison'], 'ID': 'ghoul'},
    'giant_spider': {'MAIN': {'name': 'Giant Spider', 'level': '1', 'xp': '200', 'max_hp': '26', 'ac': '14', 'physical_state': 'normal', 'max_speed': '30', 'hit_dice': ['0'], 'defined_initiative': '0', 'char_class': 'large beast', 'passive_perception': '10'}, 'ABILITIES': {'con': '12', 'int': '2', 'wis': '11', 'cha': '4', 'dex': '16', 'str': '14'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '0', 'survival': '0', 'perception': '0', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '0', 'deception': '0', 'stealth': '7', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['spider_climb', 'web_sense', 'web_walker', 'spider_bite', 'darkvision', 'blind_sight', 'web'], 'EQUIPMENT': {'equipment': ['natural armor', 'random(0)'], 'equipment on': [''], 'money': ['']}, 'SPECIAL': [], 'ID': 'giant_spider'},
    'goblin': {'MAIN': {'name': '', 'level': '0', 'xp': '50', 'max_hp': '7', 'ac': '15', 'physical_state': 'normal', 'max_speed': '30', 'hit_dice': ['6', '1', '2'], 'defined_initiative': '0', 'char_class': 'goblin', 'passive_perception': '9'}, 'ABILITIES': {'con': '10', 'int': '10', 'wis': '8', 'cha': '8', 'dex': '14', 'str': '8'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '0', 'survival': '0', 'perception': '0', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '0', 'deception': '0', 'stealth': '6', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['nimble_escape', 'darkvision'], 'EQUIPMENT': {'equipment': ['leather armor', 'scimitar', 'shield', 'shortbow', 'random(0)'], 'equipment on': ['scimitar', 'shortbow'], 'money': ['random(1)']}, 'SPECIAL': [], 'ID': 'goblin'},
    'grick': {'MAIN': {'name': 'Grick', 'level': '2', 'xp': '450', 'max_hp': '27', 'ac': '14', 'physical_state': 'normal', 'max_speed': '30', 'hit_dice': ['6', '2', '2'], 'defined_initiative': '0', 'char_class': 'monstrosity', 'passive_perception': '12'}, 'ABILITIES': {'con': '11', 'int': '3', 'wis': '14', 'cha': '5', 'dex': '14', 'str': '14'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '0', 'survival': '0', 'perception': '0', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '0', 'deception': '0', 'stealth': '0', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['stone_camouflage', 'darkvision', 'beak', 'multiattack'], 'EQUIPMENT': {'equipment': ['natural armor', 'random(2)'], 'equipment on': [''], 'money': ['']}, 'SPECIAL': ['resistance.damage.bludgeoning', 'resistance.damage.piercing', 'resistance.damage.slashing'], 'ID': 'grick'},
    'hobgoblin': {'MAIN': {'name': '', 'level': '1', 'xp': '100', 'max_hp': '11', 'ac': '18', 'physical_state': 'normal', 'max_speed': '30', 'hit_dice': ['8', '1', '1'], 'defined_initiative': '0', 'char_class': 'hobgoblin', 'passive_perception': '10'}, 'ABILITIES': {'con': '12', 'int': '10', 'wis': '10', 'cha': '9', 'dex': '12', 'str': '13'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '0', 'survival': '0', 'perception': '0', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '0', 'deception': '0', 'stealth': '0', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['martial advantage', 'darkvision'], 'EQUIPMENT': {'equipment': ['chain mail', 'shield', 'longsword', 'longbow', 'random(1)'], 'equipment on': ['longsword', 'longbow'], 'money': ['random(0)']}, 'SPECIAL': [], 'ID': 'hobgoblin'},
    'mormesk_the_wraith': {'MAIN': {'name': 'Mormesk', 'level': '3', 'xp': '700', 'max_hp': '45', 'ac': '13', 'physical_state': 'normal', 'max_speed': '60', 'hit_dice': ['8', '3', '3'], 'defined_initiative': '0', 'char_class': 'undead', 'passive_perception': '12'}, 'ABILITIES': {'con': '16', 'int': '12', 'wis': '14', 'cha': '15', 'dex': '16', 'str': '6'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '0', 'survival': '0', 'perception': '0', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '0', 'deception': '0', 'stealth': '0', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['incorporeal_movement', 'sunlight_sensitivity', 'life_drain', 'darkvision'], 'EQUIPMENT': {'equipment': ['random(3)'], 'equipment on': '0', 'money': ['random(3)']}, 'SPECIAL': ['resistance.damage.acid', 'resistance.damage.cold', 'resistance.damage.fire', 'resistance.damage.lighting', 'resistance.damage.thunder', 'resistance.damage.bludgeoning', 'resistance.damage.piercing', 'resistance.damage.slashing', 'vulnerability.damage.silver', 'immunity.damage.necrotic', 'immunity.damage.poison', 'immunity.physical_state.grappled', 'immunity.physical_state.paralized', 'immunity.physical_state.poisoned', 'immunity.physical_state.prone', 'immunity.physical_state.restrained', 'immunity.mental_state.charmed', 'immunity.mental_state.petrified'], 'ID': 'mormesk_the_wraith'},
    'nezznar_the_black_spider': {'MAIN': {'name': 'Nezznar the black spider', 'level': '2', 'xp': '450', 'max_hp': '27', 'ac': '11', 'physical_state': 'normal', 'max_speed': '30', 'hit_dice': ['6', '1', '-1'], 'defined_initiative': '0', 'char_class': 'elf', 'passive_perception': '14'}, 'ABILITIES': {'con': '10', 'int': '16', 'wis': '14', 'cha': '13', 'dex': '13', 'str': '9'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '5', 'survival': '0', 'perception': '4', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '0', 'deception': '0', 'stealth': '3', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['fey_ancestry', 'sunlight_sensitivity', 'innate_spellcasting', 'spider_staff', 'darkvision', 'spellcasting'], 'EQUIPMENT': {'equipment': ['spider_staff', 'random(3)'], 'equipment on': ['spider_staff'], 'money': ['random(3)']}, 'SPECIAL': [], 'ID': 'nezznar_the_black_spider'},
    'nothic': {'MAIN': {'name': '', 'level': '2', 'xp': '450', 'max_hp': '45', 'ac': '15', 'physical_state': 'normal', 'max_speed': '30', 'hit_dice': ['6', '1', '3'], 'defined_initiative': '0', 'char_class': 'abereration', 'passive_perception': '12'}, 'ABILITIES': {'con': '16', 'int': '13', 'wis': '10', 'cha': '8', 'dex': '16', 'str': '14'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '3', 'survival': '0', 'perception': '2', 'medicine': '0', 'insight': '4', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '0', 'deception': '0', 'stealth': '5', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['keen_sight', 'true_sight', 'claws', 'weird_sight', 'rotting_gaze', 'multiattack'], 'EQUIPMENT': {'equipment': ['natural_armor', 'random(2)'], 'equipment on': '0', 'money': ['random(2)']}, 'SPECIAL': [], 'ID': 'nothic'},
    'ochre_jelly': {'MAIN': {'name': 'Ochre jelly', 'level': '2', 'xp': '450', 'max_hp': '45', 'ac': '8', 'physical_state': 'normal', 'max_speed': '10', 'hit_dice': ['6', '2', '2'], 'defined_initiative': '0', 'char_class': 'large ooze', 'passive_perception': '8'}, 'ABILITIES': {'con': '14', 'int': '2', 'wis': '6', 'cha': '1', 'dex': '6', 'str': '15'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '0', 'survival': '0', 'perception': '0', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '0', 'deception': '0', 'stealth': '0', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['amorphous', 'spider_climb', 'pseudo_pod', 'split', 'blind_sight'], 'EQUIPMENT': {'equipment': ['random(2)'], 'equipment on': '0', 'money': '0'}, 'SPECIAL': ['resistance.damage.acid', 'immunity.damage.lighting', 'immunity.damage.slashing', 'immunity.physical_state.blinded', 'immunity.physical_state.prone', 'immunity.mental_state.charmed', 'immunity.mental_state.deafened', 'immunity.mental_state.frightened'], 'ID': 'ochre_jelly'},
    'ogre': {'MAIN': {'name': '', 'level': '2', 'xp': '450', 'max_hp': '59', 'ac': '11', 'physical_state': 'normal', 'max_speed': '40', 'hit_dice': ['8', '2', '4'], 'defined_initiative': '0', 'char_class': 'ogre', 'passive_perception': '8'}, 'ABILITIES': {'con': '16', 'int': '5', 'wis': '7', 'cha': '7', 'dex': '8', 'str': '19'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '0', 'survival': '0', 'perception': '0', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '0', 'deception': '0', 'stealth': '0', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['darkvision'], 'EQUIPMENT': {'equipment': ['greatclub', 'javelin', 'hide_armor', 'random(2)'], 'equipment on': ['greatclub', 'javelin'], 'money': ['random(0)']}, 'SPECIAL': [], 'ID': 'ogre'},
    'orc': {'MAIN': {'name': '', 'level': '1', 'xp': '100', 'max_hp': '15', 'ac': '13', 'physical_state': 'normal', 'max_speed': '30', 'hit_dice': ['12', '1', '3'], 'defined_initiative': '0', 'char_class': 'Ork', 'passive_perception': '10'}, 'ABILITIES': {'con': '16', 'int': '7', 'wis': '11', 'cha': '10', 'dex': '12', 'str': '16'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '0', 'survival': '0', 'perception': '0', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '2', 'deception': '0', 'stealth': '0', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['aggressive', 'darkvision'], 'EQUIPMENT': {'equipment': ['great_axe', 'javelin', 'hide_armor', 'random(1)'], 'equipment on': ['great_axe', 'javelin'], 'money': ['random(1)']}, 'SPECIAL': [], 'ID': 'orc'},
    'owlbear': {'MAIN': {'name': 'Owlbear', 'level': '3', 'xp': '700', 'max_hp': '59', 'ac': '13', 'physical_state': 'normal', 'max_speed': '40', 'hit_dice': ['10', '1', '5'], 'defined_initiative': '0', 'char_class': 'Large monstrosity', 'passive_perception': '13'}, 'ABILITIES': {'con': '17', 'int': '3', 'wis': '12', 'cha': '7', 'dex': '12', 'str': '20'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '0', 'survival': '0', 'perception': '3', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '0', 'deception': '0', 'stealth': '0', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['darkvision', 'keen_sight_and_smell', 'multiattack', 'beak', 'claws'], 'EQUIPMENT': {'equipment': ['natural_armor'], 'equipment on': '0', 'money': '0'}, 'SPECIAL': [], 'ID': 'owlbear'},
    'redbrand_ruffian': {'MAIN': {'name': '', 'level': '1', 'xp': '100', 'max_hp': '16', 'ac': '14', 'physical_state': 'normal', 'max_speed': '30', 'hit_dice': ['6', '1', '2'], 'defined_initiative': '0', 'char_class': 'Bandid', 'passive_perception': '9'}, 'ABILITIES': {'con': '12', 'intimidation': '9', 'wis': '9', 'cha': '11', 'dex': '14', 'str': '11'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '0', 'survival': '0', 'perception': '0', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '2', 'deception': '0', 'stealth': '0', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['multiattack'], 'EQUIPMENT': {'equipment': ['shortsword', 'studded_leather_armor', 'random(1)'], 'equipment on': ['shortsword'], 'money': ['random(1)']}, 'SPECIAL': [], 'ID': 'redbrand_ruffian'},
    'sildar_hallwinter': {'MAIN': {'name': 'Sildar Hallwinter', 'level': '1', 'xp': '200', 'max_hp': '27', 'ac': '16', 'physical_state': 'normal', 'max_speed': '30', 'hit_dice': ['8', '1', '1'], 'defined_initiative': '0', 'char_class': 'sellsword', 'passive_perception': '12'}, 'ABILITIES': {'con': '12', 'int': '10', 'wis': '11', 'cha': '10', 'dex': '10', 'str': '13'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '0', 'survival': '0', 'perception': '2', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '0', 'deception': '0', 'stealth': '0', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['multiattack', 'parry'], 'EQUIPMENT': {'equipment': ['longsword', 'heavy_crossbow', 'chain_mail', 'random(2)'], 'equipment on': ['longsword', 'heavy_crossbow'], 'money': ['random(2)']}, 'SPECIAL': [], 'ID': 'sildar_hallwinter'},
    'skeleton': {'MAIN': {'name': 'Skeleton', 'level': '1', 'xp': '50', 'max_hp': '13', 'ac': '13', 'physical_state': 'normal', 'max_speed': '30', 'hit_dice': ['6', '1', '2'], 'defined_initiative': '0', 'char_class': 'undead', 'passive_perception': '9'}, 'ABILITIES': {'con': '15', 'int': '6', 'wis': '8', 'cha': '5', 'dex': '14', 'str': '10'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '0', 'survival': '0', 'perception': '0', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '0', 'deception': '0', 'stealth': '0', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['darkvision'], 'EQUIPMENT': {'equipment': ['armor scraps', 'shortsword', 'shortbow', 'random(1)'], 'equipment on': ['shortsword', 'shortbow'], 'money': '0'}, 'SPECIAL': ['resistance.damage.bludgeoning', 'immunity.damage.poison', 'immunity.physical_state.poisoned'], 'ID': 'skeleton'},
    'spectator': {'MAIN': {'name': 'Spectator', 'level': '3', 'xp': '700', 'max_hp': '39', 'ac': '14', 'physical_state': 'normal', 'max_speed': '30', 'hit_dice': ['4', '1', '-1'], 'defined_initiative': '0', 'char_class': 'abberration', 'passive_perception': '16'}, 'ABILITIES': {'con': '14', 'int': '13', 'wis': '14', 'cha': '11', 'dex': '14', 'str': '8'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '0', 'survival': '0', 'perception': '6', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '0', 'deception': '0', 'stealth': '0', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['darkvision', 'hover', 'spell reflection', 'create food and water', 'confusion ray', 'paralyzing ray', 'fear ray', 'wounding ray', 'telepathy'], 'EQUIPMENT': {'equipment': ['natural armor', 'random(3)'], 'equipment on': [''], 'money': '0'}, 'SPECIAL': ['immunity.physical_state.prone'], 'ID': 'spectator'},
    'strige': {'MAIN': {'name': 'Strige', 'level': '0', 'xp': '25', 'max_hp': '2', 'ac': '14', 'physical_state': 'normal', 'max_speed': '40', 'hit_dice': ['4', '1', '3'], 'defined_initiative': '0', 'char_class': 'tiny beast', 'passive_perception': '9'}, 'ABILITIES': {'con': '11', 'int': '2', 'wis': '8', 'cha': '6', 'dex': '16', 'str': '4'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '0', 'survival': '0', 'perception': '0', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '0', 'deception': '0', 'stealth': '0', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['darkvision', 'blood drain'], 'EQUIPMENT': {'equipment': '0', 'equipment on': '0', 'money': '0'}, 'SPECIAL': [], 'ID': 'strige'},
    'twig_blight': {'MAIN': {'name': 'Twig Blight', 'level': '0', 'xp': '25', 'max_hp': '4', 'ac': '13', 'physical_state': 'normal', 'max_speed': '20', 'hit_dice': ['4', '1', '1'], 'defined_initiative': '0', 'char_class': 'small plant', 'passive_perception': '9'}, 'ABILITIES': {'con': '12', 'int': '4', 'wis': '8', 'cha': '3', 'dex': '13', 'str': '6'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '0', 'survival': '0', 'perception': '0', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '0', 'deception': '0', 'stealth': '3', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['blind_sight', 'claws', 'false appearance'], 'EQUIPMENT': {'equipment': ['random(0)'], 'equipment on': '0', 'money': '0'}, 'SPECIAL': ['vulnerability.damage.fire', 'immunity.physical_state.blinded', 'immunity.physical_state.deafened'], 'ID': 'twig_blight'},
    'wolf': {'MAIN': {'name': 'Wolf', 'level': '1', 'xp': '50', 'max_hp': '11', 'ac': '13', 'physical_state': 'normal', 'max_speed': '40', 'hit_dice': ['4', '2', '2'], 'defined_initiative': '0', 'char_class': 'medium beast', 'passive_perception': '13'}, 'ABILITIES': {'con': '12', 'int': '3', 'wis': '12', 'cha': '6', 'dex': '15', 'str': '12'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '0', 'survival': '0', 'perception': '3', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '0', 'deception': '0', 'stealth': '4', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['keen hearing and smell', 'pack tactics', 'bite'], 'EQUIPMENT': {'equipment': '0', 'equipment on': '0', 'money': '0'}, 'SPECIAL': [], 'ID': 'wolf'},
    'young_green_dragon': {'MAIN': {'name': '', 'level': '8', 'xp': '3900', 'max_hp': '136', 'ac': '18', 'physical_state': 'normal', 'max_speed': '60', 'hit_dice': ['10', '2', '4'], 'defined_initiative': '0', 'char_class': 'young dragon', 'passive_perception': '17'}, 'ABILITIES': {'con': '17', 'int': '16', 'wis': '13', 'cha': '15', 'dex': '12', 'str': '19'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '0', 'survival': '0', 'perception': '7', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '0', 'deception': '5', 'stealth': '4', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['blind_sight', 'multiattack', 'bite', 'claw', 'poison breath', 'darkvision', 'amphibious'], 'EQUIPMENT': {'equipment': ['random(8)'], 'equipment on': '0', 'money': ['random(6)']}, 'SPECIAL': [], 'ID': 'young_green_dragon'},
    'zombie': {'MAIN': {'name': 'Zombie', 'level': '1', 'xp': '50', 'max_hp': '22', 'ac': '8', 'physical_state': 'normal', 'max_speed': '20', 'hit_dice': ['6', '1', '1'], 'defined_initiative': '0', 'char_class': 'undead', 'passive_perception': '8'}, 'ABILITIES': {'con': '16', 'int': '3', 'wis': '6', 'cha': '5', 'dex': '6', 'str': '13'}, 'SKILLS': {'athletics': '0', 'religion': '0', 'nature': '0', 'investigation': '0', 'history': '0', 'arcana': '0', 'survival': '0', 'perception': '0', 'medicine': '0', 'insight': '0', 'animal_handling': '0', 'persuasion': '0', 'performance': '0', 'intimidation': '0', 'deception': '0', 'stealth': '0', 'acrobatics': '0', 'sleigh_of_hand': '0'}, 'PERKS': ['undead_fortitude', 'slam'], 'EQUIPMENT': {'equipment': ['random(0)'], 'equipment on': [''], 'money': ['random(0)']}, 'SPECIAL': ['immunity.physical_state.poisoned', 'immunity.damage.poison'], 'ID': 'zombie'},
'END': 1
}


items = {
    'shield': {'name': 'Shield', 'quantity': 0, 'cost': ['10', 'gp'], 'AC': 2, 'weight': 6, 'type': 'SHIELD', 'obj': 'armor'},
    'leather': {'name': 'Leather', 'quantity': 0, 'cost': ['10', 'gp'], 'AC': 11, 'weight': 10.0, 'type': 'LIGHT ARMOR', 'obj': 'armor'},
    'studded_leather': {'name': 'Studded leather', 'quantity': 0, 'cost': ['45', 'gp'], 'AC': 12, 'weight': 13.0, 'type': 'LIGHT ARMOR', 'obj': 'armor'},
    'hide': {'name': 'Hide', 'quantity': 0, 'cost': ['10', 'gp'], 'AC': 12, 'weight': 12.0, 'type': 'MEDIUM ARMOR', 'obj': 'armor'},
    'chain_shirt': {'name': 'Chain shirt', 'quantity': 0, 'cost': ['50', 'gp'], 'AC': 13, 'weight': 20.0, 'type': 'MEDIUM ARMOR', 'obj': 'armor'},
    'scale_mail': {'name': 'Scale mail', 'quantity': 0, 'cost': ['50', 'gp'], 'AC': 14, 'weight': 45.0, 'type': 'MEDIUM ARMOR', 'obj': 'armor'},
    'breastplate': {'name': 'Breastplate', 'quantity': 0, 'cost': ['400', 'gp'], 'AC': 14, 'weight': 20.0, 'type': 'MEDIUM ARMOR', 'obj': 'armor'},
    'ring_mail': {'name': 'Ring Mail', 'quantity': 0, 'cost': ['30', 'gp'], 'AC': 14, 'weight': 40.0, 'type': 'HEAVY ARMOR', 'obj': 'armor'},
    'chain_mail': {'name': 'Chain Mail', 'quantity': 0, 'cost': ['75', 'gp'], 'AC': 16, 'weight': 55.0, 'type': 'HEAVY ARMOR', 'obj': 'armor'},
    'splint': {'name': 'Splint', 'quantity': 0, 'cost': ['200', 'gp'], 'AC': 17, 'weight': 60.0, 'type': 'HEAVY ARMOR', 'obj': 'armor'},
    'club': {'name': 'Club', 'quantity': 0, 'cost': ['1', 'sp'], 'damage': ['1', '4', 'bludgeoing'], 'weight': 2.0, 'type': 'SIMPLE MELEE WEAPONS', 'obj': 'weapon'},
    'dagger': {'name': 'Dagger', 'quantity': 0, 'cost': ['2', 'gp'], 'damage': ['1', '4', 'piercing'], 'weight': 1.0, 'type': 'SIMPLE MELEE WEAPONS', 'obj': 'weapon'},
    'greatclub': {'name': 'Greatclub', 'quantity': 0, 'cost': ['2', 'sp'], 'damage': ['1', '8', 'bludgeoing'], 'weight': 10.0, 'type': 'SIMPLE MELEE WEAPONS', 'obj': 'weapon'},
    'handaxe': {'name': 'Handaxe', 'quantity': 0, 'cost': ['5', 'gp'], 'damage': ['1', '6', 'slashing'], 'weight': 2.0, 'type': 'SIMPLE MELEE WEAPONS', 'obj': 'weapon'},
    'javelin': {'name': 'Javelin', 'quantity': 0, 'cost': ['5', 'sp'], 'damage': ['1', '6', 'piercing'], 'weight': 2.0, 'type': 'SIMPLE MELEE WEAPONS', 'obj': 'weapon'},
    'light_hammer': {'name': 'Light Hammer', 'quantity': 0, 'cost': ['2', 'gp'], 'damage': ['1', '4', 'bludgeoing'], 'weight': 2.0, 'type': 'SIMPLE MELEE WEAPONS', 'obj': 'weapon'},
    'mace': {'name': 'Mace', 'quantity': 0, 'cost': ['5', 'gp'], 'damage': ['1', '6', 'bludgeoing'], 'weight': 4.0, 'type': 'SIMPLE MELEE WEAPONS', 'obj': 'weapon'},
    'quarterstaff': {'name': 'Quarterstaff', 'quantity': 0, 'cost': ['2', 'sp'], 'damage': ['1', '6', 'bludgeoing'], 'weight': 4.0, 'type': 'SIMPLE MELEE WEAPONS', 'obj': 'weapon'},
    'spear': {'name': 'Spear', 'quantity': 0, 'cost': ['1', 'gp'], 'damage': ['1', '6', 'piercing'], 'weight': 3.0, 'type': 'SIMPLE MELEE WEAPONS', 'obj': 'weapon'},
    'light_crossbow': {'name': 'Light Crossbow', 'quantity': 0, 'cost': ['25', 'gp'], 'damage': ['1', '8', 'piercing'], 'weight': 5.0, 'type': 'SIMPLE RANGED WEAPONS', 'obj': 'weapon'},
    'shortbow': {'name': 'Shortbow', 'quantity': 0, 'cost': ['25', 'gp'], 'damage': ['1', '6', 'piercing'], 'weight': 2.0, 'type': 'SIMPLE RANGED WEAPONS', 'obj': 'weapon'},
    'battleaxe': {'name': 'Battleaxe', 'quantity': 0, 'cost': ['10', 'gp'], 'damage': ['1', '8', 'slashing'], 'weight': 4.0, 'type': 'MARTIAL MELEE WEAPONS', 'obj': 'weapon'},
    'greataxe': {'name': 'Greataxe', 'quantity': 0, 'cost': ['30', 'gp'], 'damage': ['1', '12', 'slashing'], 'weight': 7.0, 'type': 'MARTIAL MELEE WEAPONS', 'obj': 'weapon'},
    'greatsword': {'name': 'Greatsword', 'quantity': 0, 'cost': ['50', 'gp'], 'damage': ['2', '6', 'slashing'], 'weight': 6.0, 'type': 'MARTIAL MELEE WEAPONS', 'obj': 'weapon'},
    'longsword': {'name': 'Longsword', 'quantity': 0, 'cost': ['15', 'gp'], 'damage': ['1', '8', 'slashing'], 'weight': 3.0, 'type': 'MARTIAL MELEE WEAPONS', 'obj': 'weapon'},
    'maul': {'name': 'Maul', 'quantity': 0, 'cost': ['10', 'gp'], 'damage': ['2', '6', 'bludgeoing'], 'weight': 10.0, 'type': 'MARTIAL MELEE WEAPONS', 'obj': 'weapon'},
    'morningstar': {'name': 'Morningstar', 'quantity': 0, 'cost': ['15', 'gp'], 'damage': ['1', '8', 'piercing'], 'weight': 4.0, 'type': 'MARTIAL MELEE WEAPONS', 'obj': 'weapon'},
    'rapier': {'name': 'Rapier', 'quantity': 0, 'cost': ['25', 'gp'], 'damage': ['1', '8', 'piercing'], 'weight': 2.0, 'type': 'MARTIAL MELEE WEAPONS', 'obj': 'weapon'},
    'scimitar': {'name': 'Scimitar', 'quantity': 0, 'cost': ['25', 'gp'], 'damage': ['1', '6', 'slashing'], 'weight': 3.0, 'type': 'MARTIAL MELEE WEAPONS', 'obj': 'weapon'},
    'shortsword': {'name': 'Shortsword', 'quantity': 0, 'cost': ['10', 'gp'], 'damage': ['1', '6', 'piercing'], 'weight': 2.0, 'type': 'MARTIAL MELEE WEAPONS', 'obj': 'weapon'},
    'trident': {'name': 'Trident', 'quantity': 0, 'cost': ['5', 'gp'], 'damage': ['1', '6', 'piercing'], 'weight': 4.0, 'type': 'MARTIAL MELEE WEAPONS', 'obj': 'weapon'},
    'warhammer': {'name': 'Warhammer', 'quantity': 0, 'cost': ['15', 'gp'], 'damage': ['1', '8', 'bludgeoing'], 'weight': 2.0, 'type': 'MARTIAL MELEE WEAPONS', 'obj': 'weapon'},
    'hand_crossbow': {'name': 'Hand Crossbow', 'quantity': 0, 'cost': ['75', 'gp'], 'damage': ['1', '6', 'piercing'], 'weight': 3.0, 'type': 'MARTIAL RANGED WEAPONS', 'obj': 'weapon'},
    'heavy_crossbow': {'name': 'Heavy Crossbow', 'quantity': 0, 'cost': ['50', 'gp'], 'damage': ['1', '10', 'piercing'], 'weight': 18.0, 'type': 'MARTIAL RANGED WEAPONS', 'obj': 'weapon'},
    'longbow': {'name': 'Longbow', 'quantity': 0, 'cost': ['50', 'gp'], 'damage': ['1', '8', 'piercing'], 'weight': 2.0, 'type': 'MARTIAL RANGED WEAPONS', 'obj': 'weapon'},
    'gallon': {'name': 'Gallon', 'quantity': 0, 'cost': ['2', 'sp.'], 'type': 'ALE', 'obj': 'fnl'},
    'mug': {'name': 'Mug', 'quantity': 0, 'cost': ['4', 'cp.'], 'type': 'ALE', 'obj': 'fnl'},
    'inn_squalid': {'name': 'Inn Squalid', 'quantity': 0, 'cost': ['7', 'cp.'], 'type': 'INN STAY(PER DAY)', 'obj': 'fnl'},
    'inn_poor': {'name': 'Inn Poor', 'quantity': 0, 'cost': ['1', 'sp.'], 'type': 'INN STAY(PER DAY)', 'obj': 'fnl'},
    'inn_modest': {'name': 'Inn Modest', 'quantity': 0, 'cost': ['5', 'sp.'], 'type': 'INN STAY(PER DAY)', 'obj': 'fnl'},
    'inn_comfortable': {'name': 'Inn Comfortable', 'quantity': 0, 'cost': ['8', 'sp.'], 'type': 'INN STAY(PER DAY)', 'obj': 'fnl'},
    'inn_wealthy': {'name': 'Inn Wealthy', 'quantity': 0, 'cost': ['2', 'gp.'], 'type': 'INN STAY(PER DAY)', 'obj': 'fnl'},
    'inn_aristocratic': {'name': 'Inn Aristocratic', 'quantity': 0, 'cost': ['4', 'gp.'], 'type': 'INN STAY(PER DAY)', 'obj': 'fnl'},
    'meals_squalid': {'name': 'Meals Squalid', 'quantity': 0, 'cost': ['3', 'cp.'], 'type': 'MEALS(PER DAY)', 'obj': 'fnl'},
    'meals_poor': {'name': 'Meals Poor', 'quantity': 0, 'cost': ['6', 'sp.'], 'type': 'MEALS(PER DAY)', 'obj': 'fnl'},
    'meals_modest': {'name': 'Meals Modest', 'quantity': 0, 'cost': ['3', 'sp.'], 'type': 'MEALS(PER DAY)', 'obj': 'fnl'},
    'meals_comfortable': {'name': 'Meals Comfortable', 'quantity': 0, 'cost': ['5', 'sp.'], 'type': 'MEALS(PER DAY)', 'obj': 'fnl'},
    'meals_wealthy': {'name': 'Meals Wealthy', 'quantity': 0, 'cost': ['8', 'sp.'], 'type': 'MEALS(PER DAY)', 'obj': 'fnl'},
    'meals_aristocratic': {'name': 'Meals Aristocratic', 'quantity': 0, 'cost': ['2', 'gp.'], 'type': 'MEALS(PER DAY)', 'obj': 'fnl'},
    'common': {'name': 'Common', 'quantity': 0, 'cost': ['2', 'sp.'], 'type': 'WINE', 'obj': 'fnl'},
    'fine': {'name': 'Fine', 'quantity': 0, 'cost': ['10', 'gp.'], 'type': 'WINE', 'obj': 'fnl'},
    'arrow': {'name': 'Arrow', 'quantity': 0, 'cost': ['5', 'cp.'], 'weight': 0.05, 'type': 'AMMUNITION', 'obj': 'misc'},
    'crossbow_bolt': {'name': 'Crossbow bolt', 'quantity': 0, 'cost': ['5', 'cp.'], 'weight': 0.075, 'type': 'AMMUNITION', 'obj': 'misc'},
    'backpack': {'name': 'Backpack', 'quantity': 0, 'cost': ['2', 'gp.'], 'weight': 5.0, 'type': 'OTHER', 'obj': 'misc'},
    'bedroll': {'name': 'Bedroll', 'quantity': 0, 'cost': ['1', 'gp.'], 'weight': 7.0, 'type': 'OTHER', 'obj': 'misc'},
    'bell': {'name': 'Bell', 'quantity': 0, 'cost': ['1', 'gp.'], 'weight': 0.01, 'type': 'OTHER', 'obj': 'misc'},
    'blanket': {'name': 'Blanket', 'quantity': 0, 'cost': ['5', 'sp.'], 'weight': 3.0, 'type': 'OTHER', 'obj': 'misc'},
    'book': {'name': 'Book', 'quantity': 0, 'cost': ['25', 'gp.'], 'weight': 5.0, 'type': 'OTHER', 'obj': 'misc'},
    'candle': {'name': 'Candle', 'quantity': 0, 'cost': ['1', 'cp.'], 'weight': 0.01, 'type': 'OTHER', 'obj': 'misc'},
    'carpenters_tools': {'name': 'Carpenters tools', 'quantity': 0, 'cost': ['8', 'gp.'], 'weight': 6.0, 'type': 'OTHER', 'obj': 'misc'},
    'case': {'name': 'Case', 'quantity': 0, 'cost': ['1', 'gp.'], 'weight': 1.0, 'type': 'OTHER', 'obj': 'misc'},
    'chalk': {'name': 'Chalk', 'quantity': 0, 'cost': ['1', 'cp.'], 'weight': 0.01, 'type': 'OTHER', 'obj': 'misc'},
    'chest': {'name': 'Chest', 'quantity': 0, 'cost': ['5', 'gp.'], 'weight': 25.0, 'type': 'OTHER', 'obj': 'misc'},
    'clothes_common': {'name': 'Clothes common', 'quantity': 0, 'cost': ['5', 'sp.'], 'weight': 3.0, 'type': 'OTHER', 'obj': 'misc'},
    'clothes_fine': {'name': 'Clothes fine', 'quantity': 0, 'cost': ['15', 'gp.'], 'weight': 6.0, 'type': 'OTHER', 'obj': 'misc'},
    'component_poach': {'name': 'Component poach', 'quantity': 0, 'cost': ['25', 'gp.'], 'weight': 2.0, 'type': 'OTHER', 'obj': 'misc'},
    'crowbar': {'name': 'Crowbar', 'quantity': 0, 'cost': ['2', 'gp.'], 'weight': 5.0, 'type': 'OTHER', 'obj': 'misc'},
    'grapling_hook': {'name': 'Grapling hook', 'quantity': 0, 'cost': ['2', 'gp.'], 'weight': 4.0, 'type': 'OTHER', 'obj': 'misc'},
    'hammer': {'name': 'Hammer', 'quantity': 0, 'cost': ['1', 'gp.'], 'weight': 3.0, 'type': 'OTHER', 'obj': 'misc'},
    'hammer_sledge': {'name': 'Hammer sledge', 'quantity': 0, 'cost': ['2', 'gp.'], 'weight': 10.0, 'type': 'OTHER', 'obj': 'misc'},
    'healers_kit': {'name': 'Healers kit', 'quantity': 0, 'cost': ['5', 'gp.'], 'weight': 3.0, 'type': 'OTHER', 'obj': 'misc'},
    'holy_symbol': {'name': 'Holy Symbol', 'quantity': 0, 'cost': ['5', 'gp.'], 'weight': 1.0, 'type': 'OTHER', 'obj': 'misc'},
    'hourglass': {'name': 'Hourglass', 'quantity': 0, 'cost': ['25', 'gp.'], 'weight': 1.0, 'type': 'OTHER', 'obj': 'misc'},
    'ink': {'name': 'Ink', 'quantity': 0, 'cost': ['10', 'gp.'], 'weight': 0.01, 'type': 'OTHER', 'obj': 'misc'},
    'ink_pen': {'name': 'Ink pen', 'quantity': 0, 'cost': ['2', 'cp.'], 'weight': 0.01, 'type': 'OTHER', 'obj': 'misc'},
    'lantern_bullseye': {'name': 'Lantern bullseye', 'quantity': 0, 'cost': ['10', 'gp.'], 'weight': 2.0, 'type': 'OTHER', 'obj': 'misc'},
    'lantern_hooded': {'name': 'Lantern hooded', 'quantity': 0, 'cost': ['5', 'gp.'], 'weight': 2.0, 'type': 'OTHER', 'obj': 'misc'},
    'lock': {'name': 'Lock', 'quantity': 0, 'cost': ['10', 'gp.'], 'weight': 1.0, 'type': 'OTHER', 'obj': 'misc'},
    'masons_tools': {'name': 'Masons tools', 'quantity': 0, 'cost': ['10', 'gp.'], 'weight': 8.0, 'type': 'OTHER', 'obj': 'misc'},
    'mess_kit': {'name': 'Mess kit', 'quantity': 0, 'cost': ['2', 'sp.'], 'weight': 1.0, 'type': 'OTHER', 'obj': 'misc'},
    'mirror_steel': {'name': 'Mirror steel', 'quantity': 0, 'cost': ['5', 'gp.'], 'weight': 0.5, 'type': 'OTHER', 'obj': 'misc'},
    'oil': {'name': 'Oil', 'quantity': 0, 'cost': ['1', 'sp.'], 'weight': 1.0, 'type': 'OTHER', 'obj': 'misc'},
    'paper': {'name': 'Paper', 'quantity': 0, 'cost': ['2', 'sp.'], 'weight': 0.01, 'type': 'OTHER', 'obj': 'misc'},
    'perfume': {'name': 'Perfume', 'quantity': 0, 'cost': ['5', 'gp.'], 'weight': 0.01, 'type': 'OTHER', 'obj': 'misc'},
    'miners_pick': {'name': 'Miners pick', 'quantity': 0, 'cost': ['2', 'gp.'], 'weight': 10.0, 'type': 'OTHER', 'obj': 'misc'},
    'piton': {'name': 'Piton', 'quantity': 0, 'cost': ['5', 'cp.'], 'weight': 0.25, 'type': 'OTHER', 'obj': 'misc'},
    'pot_iron': {'name': 'Pot iron', 'quantity': 0, 'cost': ['2', 'gp.'], 'weight': 10.0, 'type': 'OTHER', 'obj': 'misc'},
    'potion_of_healing': {'name': 'Potion of healing', 'quantity': 0, 'cost': ['50', 'gp.'], 'weight': 0.5, 'type': 'OTHER', 'obj': 'misc'},
    'playing_cards': {'name': 'Playing cards', 'quantity': 0, 'cost': ['5', 'sp.'], 'weight': 0.01, 'type': 'OTHER', 'obj': 'misc'},
    'poach': {'name': 'Poach', 'quantity': 0, 'cost': ['5', 'sp.'], 'weight': 1.0, 'type': 'OTHER', 'obj': 'misc'},
    'rations': {'name': 'Rations ', 'quantity': 0, 'cost': ['5', 'sp.'], 'weight': 2.0, 'type': 'OTHER', 'obj': 'misc'},
    'robes': {'name': 'Robes', 'quantity': 0, 'cost': ['1', 'gp.'], 'weight': 4.0, 'type': 'OTHER', 'obj': 'misc'},
    'rope_hempen': {'name': 'Rope hempen', 'quantity': 0, 'cost': ['1', 'gp.'], 'weight': 10.0, 'type': 'OTHER', 'obj': 'misc'},
    'rope_silk': {'name': 'Rope silk', 'quantity': 0, 'cost': ['10', 'gp.'], 'weight': 5.0, 'type': 'OTHER', 'obj': 'misc'},
    'sack': {'name': 'Sack', 'quantity': 0, 'cost': ['1', 'cp.'], 'weight': 0.5, 'type': 'OTHER', 'obj': 'misc'},
    'sealing_wax': {'name': 'Sealing wax', 'quantity': 0, 'cost': ['5', 'sp.'], 'weight': 0.01, 'type': 'OTHER', 'obj': 'misc'},
    'shovel': {'name': 'Shovel', 'quantity': 0, 'cost': ['2', 'gp.'], 'weight': 5.0, 'type': 'OTHER', 'obj': 'misc'},
    'signal_whistle': {'name': 'Signal whistle', 'quantity': 0, 'cost': ['5', 'cp.'], 'weight': 0.01, 'type': 'OTHER', 'obj': 'misc'},
    'signet_ring': {'name': 'Signet ring', 'quantity': 0, 'cost': ['5', 'gp.'], 'weight': 0.01, 'type': 'OTHER', 'obj': 'misc'},
    'spell_book': {'name': 'Spell book', 'quantity': 0, 'cost': ['50', 'gp.'], 'weight': 3.0, 'type': 'OTHER', 'obj': 'misc'},
    'spike_iron': {'name': 'Spike Iron', 'quantity': 0, 'cost': ['1', 'sp.'], 'weight': 0.5, 'type': 'OTHER', 'obj': 'misc'},
    'tent': {'name': 'Tent ', 'quantity': 0, 'cost': ['2', 'gp.'], 'weight': 20.0, 'type': 'OTHER', 'obj': 'misc'},
    'thieves_tools': {'name': 'Thieves tools', 'quantity': 0, 'cost': ['25', 'gp.'], 'weight': 1.0, 'type': 'OTHER', 'obj': 'misc'},
    'tinderbox': {'name': 'Tinderbox', 'quantity': 0, 'cost': ['5', 'sp.'], 'weight': 1.0, 'type': 'OTHER', 'obj': 'misc'},
    'torch': {'name': 'Torch', 'quantity': 0, 'cost': ['1', 'cp.'], 'weight': 1.0, 'type': 'OTHER', 'obj': 'misc'},
    'waterskin': {'name': 'Waterskin', 'quantity': 0, 'cost': ['2', 'sp.'], 'weight': 5.0, 'type': 'OTHER', 'obj': 'misc'},
    'whetstone': {'name': 'Whetstone', 'quantity': 0, 'cost': ['1', 'cp.'], 'weight': 1.0, 'type': 'OTHER', 'obj': 'misc'},
    'parchment': {'name': 'Parchment', 'quantity': 0, 'cost': ['1', 'sp.'], 'weight': 0.01, 'type': 'OTHER', 'obj': 'misc'},
    'donkey': {'name': 'Donkey', 'quantity': 0, 'cost': ['8', 'gp.'], 'speed': ['40', 'ft.'], 'carrying capacity': ['420', 'lb.'], 'obj': 'mounts'},
    'horse_draft': {'name': 'Horse draft', 'quantity': 0, 'cost': ['50', 'gp.'], 'speed': ['40', 'ft.'], 'carrying capacity': ['540', 'lb.'], 'obj': 'mounts'},
    'horse_riding': {'name': 'Horse riding', 'quantity': 0, 'cost': ['75', 'gp.'], 'speed': ['60', 'ft.'], 'carrying capacity': ['480', 'lb.'], 'obj': 'mounts'},
    'bit_and_bridle': {'name': 'Bit and bridle', 'quantity': 0, 'cost': ['2', 'gp.'], 'weight': 1.0, 'type': 'FOOD', 'obj': 'tnh'},
    'food': {'name': 'Food', 'quantity': 0, 'cost': ['5', 'cp.'], 'weight': 10.0, 'type': 'FOOD', 'obj': 'tnh'},
    'pack': {'name': 'Pack', 'quantity': 0, 'cost': ['5', 'gp.'], 'weight': 15.0, 'type': 'SADDLE', 'obj': 'tnh'},
    'riding': {'name': 'Riding', 'quantity': 0, 'cost': ['10', 'gp.'], 'weight': 25.0, 'type': 'SADDLE', 'obj': 'tnh'},
    'saddlebags': {'name': 'Saddlebags', 'quantity': 0, 'cost': ['4', 'gp.'], 'weight': 8.0, 'type': 'SADDLE', 'obj': 'tnh'},
    'stabling': {'name': 'Stabling', 'quantity': 0, 'cost': ['5', 'sp.'], 'weight': 0, 'type': 'SADDLE', 'obj': 'tnh'}
}

itemlist_0 = ['hide', 'splint', 'club', 'dagger', 'arrow', 'crossbow_bolt', 'backpack', 'bell', 'blanket', 'book', 'candle', 'chalk', 'clothes_common', 'clothes_fine', 'holy_symbol', 'ink', 'hourglass', 'paper', 'piton', 'playing_cards', 'rations', 'robes', 'rope_hempen', 'rope_silk', 'signet_ring', 'signal_whistle', 'tinderbox', 'whetstone', 'waterskin']
itemlist_1 = ['shield', 'leather', 'studded_leather', 'chain_shirt', 'chain_mail', 'ring_mail', 'splint', 'club', 'dagger', 'greatclub', 'handaxe', 'javelin', 'light_hammer', 'mace', 'spear', 'light_crossbow', 'shortbow', 'battleaxe', 'longsword', 'maul', 'rapier', 'shortsword', 'trident', 'hand_crossbow', 'longbow', 'carpenters_tools', 'clothes_common', 'clother_fine', 'component_pouch', 'crowbar', 'grapling_hook', 'hammer', 'ink_pen', 'lantern_hooded', 'masons_tools', 'mirror_steel', 'mess_kit', 'oil', 'pot_iron', 'rations', 'rope_silk', 'sack', 'sealing_wax', 'signet_ring', 'torch', 'waterskin', 'whetstone']
itemlist_2 = itemlist_1 + ['thieves_tools', 'tent', 'signet_ring', 'shovel', 'rope_hempen', 'playing_cards', 'potion_of_healing', 'lantern_hooded', 'lantern_bullseye', 'healers_kit', 'arrow', 'crossbow_bolt', 'heavy_crossbow', 'warhammer', 'trident']
itemlist_3 = itemlist_2 + ['saddlebag', 'parchment', 'robes', 'case', 'quarterstaff']
itemlist_8 = itemlist_3 + itemlist_0

itemlist = [itemlist_0, itemlist_1, itemlist_2, itemlist_3, itemlist_8]


perks = {'parry': {'type': 'active', 'group': 'creature_method', 'relevance': 'high'}, # TODO: Type and groups -> Perks classes/methods -> Creature.addMethod(Method)
         'amorphous': {'type': 'passive', 'group': 'cosmetic', 'relevance': 'low'},
         'darkvision': {'type': 'passive', 'group': 'modifier', 'relevance': 'high'},
         'fey_ancestry': {'type': 'passive', 'group': 'modifier', 'relevance': 'low'},
         'blind_sight': {'type': 'passive', 'group': 'cosmetic', 'relevance': 'low'},
         'illumination': {'type': 'passive', 'group': 'cosmetic', 'relevance': 'high'},
         'false_appearance': {'type': 'active', 'group': 'creature_method', 'relevance': 'high'},
         'paralyzing_ray': {'type': 'active', 'group': 'creature_method', 'relevance': 'high'},
         'claw': {'type': 'active', 'group': 'weapon', 'relevance': 'high'},
         'life_drain': {'type': 'active', 'group': 'creature_method', 'relevance': 'high'},
         'criminal_contact': {'type': 'passive', 'group': 'plot', 'relevance': 'low'},
         'lucky': {'type': 'passive', 'group': 'modifier', 'relevance': 'medium'},
         'true_sight': {'type': 'passive', 'group': 'cosmetic', 'relevance': 'low'},
         'naturally_stealthy': {'type': 'passive', 'group': 'modifier', 'relevance': 'high'},
         'brave': {'type': 'passive', 'group': 'modifier', 'relevance': 'medium'},
         'blood_drain': {'type': 'active', 'group': 'creature_method', 'relevance': 'high'},
         'pack_tactics': {'type': 'passive', 'group': 'cosmetic', 'relevance': 'high'},
         'spell_reflection': {'type': 'passive', 'group': 'modifier', 'relevance': 'medium'},
         'rotting_gaze': {'type': 'active', 'group': 'creature_method', 'relevance': 'high'},
         'thieves_cant': {'type': 'passive', 'group': 'cosmetic', 'relevance': 'medium'},
         'telepathy': {'type': 'passive', 'group': 'cosmetic', 'relevance': 'low'},
         'position_of_privilege': {'type': 'passive', 'group': 'plot', 'relevance': 'low'},
         'stone_camouflage': {'type': 'active', 'group': 'modifier', 'relevance': 'medium'},
         'keen_sight': {'type': 'passive', 'group': 'cosmetic', 'relevance': 'low'},
         'brute': {'type': 'passive', 'group': 'modifier', 'relevance': 'low'},
         'magic_resistance': {'type': 'passive', 'group': 'modifier', 'relevance': 'high'},
         'beak': {'type': 'active', 'group': 'weapon', 'relevance': 'high'},
         'pseudo_pod': {'type': 'passive', 'group': 'cosmetic', 'relevance': 'low'},
         'undead_fortitude': {'type': 'passive', 'group': 'modifier', 'relevance': 'medium'},
         'web_walker': {'type': 'passive', 'group': 'cosmetic', 'relevance': 'low'},
         'spellcasting': {'type': 'passive', 'group': 'cosmetic', 'relevance': 'high'},
         'innate_spellcasting': {'type': 'passive', 'group': 'cosmetic', 'relevance': 'high'},
         'slam': {'type': 'active', 'group': 'creature_method', 'relevance': 'high'},
         'create_food_and_water': {'type': 'active', 'group': 'creature_method', 'relevance': 'medium'},
         'split': {'type': 'active', 'group': 'creature_method', 'relevance': 'high'},
         'fighting_style_defense': {'type': 'passive', 'group': 'modifier', 'relevance': 'medium'},
         'second_wind': {'type': 'active', 'group': 'creature_method', 'relevance': 'high'},
         'fighting_style_archery': {'type': 'passive', 'group': 'modifier', 'relevance': 'medium'},
         'rustic_hospitality': {'type': 'passive', 'group': 'plot', 'relevance': 'low'},
         'multiattack': {'type': 'active', 'group': 'creature_method', 'relevance': 'high'},
         'wounding_ray': {'type': 'active', 'group': 'creature_method', 'relevance': 'high'},
         'aggressive': {'type': 'passive', 'group': 'modifier', 'relevance': 'low'},
         'devotion': {'type': 'passive', 'group': 'plot', 'relevance': 'low'},
         'poison_breath': {'type': 'active', 'group': 'creature_method', 'relevance': 'high'},
         'hover': {'type': 'passive', 'group': 'cosmetic', 'relevance': 'medium'},
         'web_sense': {'type': 'passive', 'group': 'cosmetic', 'relevance': 'high'},
         'web': {'type': 'active', 'group': 'creature_method', 'relevance': 'high'},
         'incorporeal_movement': {'type': 'passive', 'group': 'cosmetic', 'relevance': 'low'},
         'surprise_attack': {'type': 'active', 'group': 'creature_method', 'relevance': 'medium'},
         'confusion_ray': {'type': 'active', 'group': 'creature_method', 'relevance': 'high'},
         'weird_sight': {'type': 'passive', 'group': 'modifier', 'relevance': 'medium'},
         'bite': {'type': 'active', 'group': 'creature_method', 'relevance': 'high'},
         'martial_advantage': {'type': 'passive', 'group': 'modifier', 'relevance': 'medium'},
         'rejuvenation': {'type': 'active', 'group': 'creature_method', 'relevance': 'medium'},
         'trance': {'type': 'passive', 'group': 'cosmetic', 'relevance': 'low'},
         'arcane_recovery': {'type': 'active', 'group': 'creature_method', 'relevance': 'medium'},
         'nimble_escape': {'type': 'active', 'group': 'modifier', 'relevance': 'medium'},
         'claws': {'type': 'active', 'group': 'weapon', 'relevance': 'high'},
         'spider_climb': {'type': 'passive', 'group': 'cosmetic', 'relevance': 'low'},
         'ambush': {'type': 'active', 'group': 'creature_method', 'relevance': 'high'},
         'halfling_nimbleness': {'type': 'passive', 'group': 'modifier', 'relevance': 'low'},
         'spider_bite': {'type': 'active', 'group': 'creature_method', 'relevance': 'high'},
         'amphibious': {'type': 'passive', 'group': 'cosmetic', 'relevance': 'low'},
         'fear_ray': {'type': 'active', 'group': 'creature_method', 'relevance': 'high'},
         'sunlight_sensitivity': {'type': 'passive', 'group': 'cosmetic', 'relevance': 'low'},
         'keen_sight_and_smell': {'type': 'passive', 'group': 'cosmetic', 'relevance': 'low'},
         'read_thoughts': {'type': 'active', 'group': 'creature_method', 'relevance': 'high'},
         'keen_hearing_and_smell': {'type': 'passive', 'group': 'modifier', 'relevance': 'low'},
         'shelter_of_the_faithful': {'type': 'passive', 'group': 'cosmetic', 'relevance': 'low'},
         'sneak_attack': {'type': 'passive', 'group': 'modifier', 'relevance': 'high'},
         'disciple_of_life': {'type': 'passive', 'group': 'modifier', 'relevance': 'high'},
         'dwarven_resilience': {'type': 'passive', 'group': 'modifier', 'relevance': 'high'},
         'dwarven_toughness': {'type': 'passive', 'group': 'modifier', 'relevance': 'high'},
         }


spells = {} #TODO: Add spells


def choosePerks(type=None, group=None, relevance=None):
    grouped = {}
    prioritized = {}
    typed = {}
    if type != None:
        for perk, value in perks.items():
            if perks[perk]["type"] == type:
                typed[perk] = value
    else:
        typed = perks.copy()
    if group != None:
        for perk, value in typed.items():
            if typed[perk]["group"] == group:
                grouped[perk] = value
    else:
        grouped = typed
    if relevance != None:
        for perk, value in grouped.items():
            if grouped[perk]["relevance"] == relevance:
                prioritized[perk] = value
    else:
        prioritized = grouped
    return prioritized




if __name__ == "__main__":


    my_perks = choosePerks("active", 'creature_method')
    for k,v in my_perks.items():
        print(k,v)


